import type { Move } from "#app/data/move";
import type { Pokemon } from "#app/field/pokemon";
import { Abilities } from "#enums/abilities";
import { StatusEffect } from "#enums/status-effect";
import { ElementalType } from "#enums/elemental-type";
import { PostDefendAbAttr } from "./post-defend-ab-attr";
import { MoveFlags } from "#enums/move-flags";
import { AbAttrFlag } from "#enums/ab-attr-flag";

/**
 * Effect Spore's ability attribute
 *
 * When a Pokémon with this Ability is hit by a move that makes contact, there is a 9% chance of poison, 10% chance of paralysis, and 11% chance of sleep.
 * The total sum of these chances is 30%.
 * @extends PostDefendAbAttr
 */
export class EffectSporeAbAttr extends PostDefendAbAttr {
  public readonly chance = 30;

  constructor(showAbility: boolean = true, showAbilityInstant: boolean = false) {
    super(showAbility, showAbilityInstant);
    this._flags.add(AbAttrFlag.EFFECT_SPORE);
  }

  /**
   * Identical code to {@linkcode PostDefendContactApplyStatusEffectAbAttr}'s `applyPostDefend()` but it contains two conditional checks.
   * Effect Spore cannot affect the attacker if the attacker is Grass-type or has the ability Overcoat
   */
  override apply(pokemon: Pokemon, simulated: boolean, attacker: Pokemon, move: Move): boolean {
    if (attacker.hasAbility(Abilities.OVERCOAT) || attacker.isOfType(ElementalType.GRASS)) {
      return false;
    }
    const roll = pokemon.randSeedInt(100);
    if (
      move.checkFlag(MoveFlags.MAKES_CONTACT, attacker, pokemon)
      && !attacker.hasNonVolatileStatusEffect()
      && roll < this.chance
    ) {
      const statusEffect = this.getStatus(roll);
      if (simulated) {
        return attacker.canSetStatus(statusEffect, true, false, pokemon);
      } else {
        return attacker.trySetStatus(statusEffect, true, pokemon);
      }
    }
    return false;
  }

  /**
   * Returns a status effect based on the ability's roll
   * @param roll a number between 0 and 99 generated by randSeedInt
   * @returns a status effect that is either sleep, paralysis, or poison
   */
  private getStatus(roll: number): StatusEffect {
    const SLEEP_THRESHOLD = 11;
    const PARA_THRESHOLD = 10 + SLEEP_THRESHOLD;
    const PSN_THRESHOLD = 9 + PARA_THRESHOLD;
    if (roll < SLEEP_THRESHOLD) {
      return StatusEffect.SLEEP;
    } else if (roll < PARA_THRESHOLD) {
      return StatusEffect.PARALYSIS;
    } else if (roll < PSN_THRESHOLD) {
      return StatusEffect.POISON;
    }
    return StatusEffect.NONE;
  }
}
